type: mysql
# root:root@tcp(localhost:3306)/jwt_demo?parseTime=true
username: root
password: root
protocol: tcp
server: localhost
port: 3306
db-name: jwt_demo
options:
  - parseTime=true
  - charset=utf8mb4
  - loc=local